apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mtls-ingress
  annotations:
    haproxy-ingress.github.io/auth-tls-secret: client-ca-cert
    haproxy-ingress.github.io/auth-tls-strict: true
    haproxy-ingress.github.io/auth-tls-verify-client: on
    # forwards client cert to backend for app-based authx
    haproxy-ingress.github.io/auth-tls-cert-header: true
spec:
  ingressClassName: example
  rules:
    host: mtls-ingress.example.cluster
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-a
            port:
              number: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: client-ca-cert
type: Opaque
data:
  ca.crt: |-
-----BEGIN CERTIFICATE-----
MIIDPzCCAiegAwIBAgIUJRG9naHcUJaVyds/kzMewslrxC0wDQYJKoZIhvcNAQEL
BQAwLzELMAkGA1UEBhMCREsxIDAeBgNVBAMMF2hhcHJveHktaW5ncmVzcy1jbGll
bnRzMB4XDTIyMDIwMTA5MDM0NFoXDTI3MDEzMTA5MDM0NFowLzELMAkGA1UEBhMC
REsxIDAeBgNVBAMMF2hhcHJveHktaW5ncmVzcy1jbGllbnRzMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxg8imrum02kVf27kOsmBYUBNPgDkFfVEhdM1
GTLT0Ed3yM1BSArIMeGG5Zjvz+oQvgK83WEhpYvcmrgHWHwoIO/pILMSPbmq8OXF
nGG2umhZ7laE45BNuimInSICpQ5fTaJSY87xeHgZoq/SESqY57+r4t3oG9ySeb7j
BnFuBBigXHlHhmTqOZ9TFj56aBmuYWRM/dcdx81j6M3FrdMHhmGwR7MJeixkEwYA
w+LMfLoUSa1gC5KouMgDV4noaZPHrzqfuAqUhFIlL9GE8HkY1keyLhCKFNDwyua8
Q6zmRMuOmHzHzOxofox8zU0C7qVw/dpJ6pWLnCCAvamfi9yvoQIDAQABo1MwUTAd
BgNVHQ4EFgQU+/DxzuFctFfFW3YSwa3JKVz5JiUwHwYDVR0jBBgwFoAU+/DxzuFc
tFfFW3YSwa3JKVz5JiUwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
AQEAo0EmnNzq1SHO0US7E/0b6JOItrS5cXfSyrP5whJIgK3elcCmgQPbVQ+XnpVI
5ph04ACDvTjeqU2kWUrvOps3jpqZM1D4J5pIHgbH9BYV7jv/0WRK6nlwyTxe9e0T
XyT8X8neG7v9yT4jLoRYkvgGjE0RJqtngU7iaE0qwyemakuIlZAYo2OerjZqsZbc
tue7Pyn1vl+RcnpcLl6R6aHXZenaOTa2CK4t7YubHOOlg9TjFaD7e6tHXg5ozBKi
bpLXji/YyAu4BplLZkqOS4XiyQ5j5cldFDc7wBSuVccSamRB3lis/e+ushDhDXSz
jLUq4Ue6mD+sIxDcXRU9Nb9T5w==
-----END CERTIFICATE-----
